/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liangjie_app_NativeUtil */

#ifndef _Included_liangjie_app_NativeUtil
#define _Included_liangjie_app_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liangjie_app_NativeUtil
 * Method:    SayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_liangjie_app_NativeUtil_SayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
